# Used only by the pages:build script to bundle worker.js via wrangler dry-run
name = "hr-quiz"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
